problems:
  # Problem 1
  # min   -4*x-3y-5z
  # s.t.  2x+3y+z-12 <= 0
  #       2x+y+3z-12 <= 0
  #       z <= 20
  #       x, y, z >= 0
  #       z integer
  - name: problem1
    num_con_variable: 2
    num_int_variable: 1
    int_bounds:
      upper: [20]
      lower: [0]
    con_bounds:
      upper: [10.0, 10.0]
      lower: [0.0, 0.0]
    objective_dims:
      rows: 4
      cols: 1
    constraint_dims:
      rows: 4
      cols: 2
    lambda_dims:
      rows: 2
      cols: 1
    objective_matrix: [-4, -3, -5, 0]
    constraint_matrix: [2, 2, 3, 1, 1, 3, -12, -12]
    lambda_matrix: [10, 10]
    evolve_params:
      max_lambda: 100
      init_lambda: 1
      max_evolve_round: 60
      accuracy_rng: 0.5
      elite_eval_count: 8

  # Problem 1
  # min   -4*x-3y-5z
  # s.t.  2x+3y+z-12 <= 0
  #       2x+y+3z-12 <= 0
  #       z <= 20
  #       x, y, z >= 0
  #       z integer
  - name: problem2
    num_con_variable: 2
    num_int_variable: 1
    int_bounds:
      upper: [20]
      lower: [0]
    con_bounds:
      upper: [10.0, 10.0]
      lower: [0.0, 0.0]
    objective_dims:
      rows: 4
      cols: 1
    constraint_dims:
      rows: 4
      cols: 2
    lambda_dims:
      rows: 2
      cols: 1
    objective_matrix: [-4, -3, -5, 0]
    constraint_matrix: [2, 2, 3, 1, 1, 3, -12, -12]
    lambda_matrix: [10, 10]
    evolve_params:
      max_lambda: 100
      init_lambda: 1
      max_evolve_round: 60
      accuracy_rng: 0.5
      elite_eval_count: 8